version: '3.7'

services:
  web:
    build:
      context: ./discounts_finder/
    volumes:
      - ./discounts_finder:/discounts_finder/
    ports:
      - "5000:5000"
    env_file:
      - ./discounts_finder/.env.dev
    depends_on:
      - redis
      - mongodb
  mongodb:
    image: mongo:4.4.5-bionic
    container_name: mongodb
    command: mongod --auth
    env_file:
      - ./discounts_finder/.env.dev
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
  celery-worker:
    build:
      context: ./discounts_finder/
    command: "celery -A celery_worker.celery_init.celery worker -l info"
    user: root
    depends_on:
      - redis
    env_file:
      - ./discounts_finder/.env.dev
    volumes:
      - ./discounts_finder:/discounts_finder
