version: '3.7'

services:
  web:
    build:
      context: ./discounts_finder/
      target: web
    volumes:
      - ./discounts_finder:/discounts_finder/
    ports:
      - "5000:5000"
    env_file:
      - ./discounts_finder/.env.dev
    depends_on:
      - redis
      - mongodb
  mongodb:
    image: mongo:4.4.5-bionic
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    env_file:
      - ./discounts_finder/.env.dev
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis:alpine
  celery-worker:
    working_dir: /discounts_finder
    build:
      context: ./discounts_finder/
      target: celery_worker
    user: root
    depends_on:
      - redis
    env_file:
      - ./discounts_finder/.env.dev
    volumes:
      - ./discounts_finder:/discounts_finder
  celery-beat:
    working_dir: /discounts_finder
    build:
      context: ./discounts_finder/
      target: celery_beat
    user: root
    depends_on:
      - redis
    env_file:
      - ./discounts_finder/.env.dev
    volumes:
      - ./discounts_finder:/discounts_finder
volumes:
  mongodbdata:
    driver: local