version: '3.7'

services:
  web:
    build: ./discounts_finder/
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./discounts_finder:/discounts_finder/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - mongodb
  mongodb:
    image: mongo:4.4.5-bionic
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    env_file:
      - ./.env.dev
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis:alpine
  celery-worker:
    working_dir: /discounts_finder
    build:
      context: ./discounts_finder/
    command: celery -A celery_queue.celery_init.celery worker -l info --uid=nobody --gid=nogroup
    user: root
    depends_on:
      - redis
    env_file:
      - ./.env.dev
    volumes:
      - ./discounts_finder:/discounts_finder
  celery-beat:
    working_dir: /discounts_finder
    build:
      context: ./discounts_finder/
    command: celery -A celery_queue.celery_init.celery beat -l info
    user: root
    depends_on:
      - redis
    env_file:
      - ./.env.dev
    volumes:
      - ./discounts_finder:/discounts_finder
volumes:
  mongodbdata:
    driver: local