version: '3.7'

services:
  web:
    build: ./discounts_finder/
    command: python app.py runserver --host 0.0.0.0
    volumes:
        - ./discounts_finder:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker_db
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
  worker:
    build:
      context: ./discounts_finder/
      args:
        - FLASK_ENV=${FLASK_ENV:-production}
    command: celery -A app.celery worker -l info
    user: nobody
    depends_on:
      - redis
    env_file:
      - ./.env.dev
    volumes:
      - ./public:/app/public

