apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: discounts-finder-app
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 5000
  type: LoadBalancer
