apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-map
data:
  # property-like keys; each key maps to a simple value
  flask-app: "app.py"
  flask-env: "development"
  celery-broker-url: "redis://redis:6379"
